name: Run Tasks

on:
  push:

jobs:
  run-task:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        task: [coloring]

    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      # standard compiler in ubuntu-latest is gcc
      # it doesn't support <print>
      - name: Install Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: latest
          platform: x64

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          export CXX=clang
          cmake -B build -S .

      - name: Build
        run: cmake --build build -j

      - name: Run task
        run: |
          echo "Running ${{ matrix.task }}"
          cmake --build build --target ${{ matrix.task }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.task }}
          path: outputs/${{ matrix.task }}
